source {C:/Xilinx/data/projnav/scripts/VsimStopServer.tcl}
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vlog  "dual_ram_core.v"
vlog  "SquareWave.v"
vlog  "dual_ram.v"
vlog  "aa.ant"
vlog  "C:/Xilinx/verilog/src/glbl.v"
vsim -t 1ps   -L xilinxcorelib_ver -L unisims_ver -lib work aa glbl
run -all
quit -force
